services:
  # Beets - Music library manager and tagger
  beets:
    image: lscr.io/linuxserver/beets:latest
    container_name: beets
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "tools", "all"]
    networks:
      - reverse_proxy
    volumes:
      - $DOCKERDIR/appdata/beets:/config
      - $DOCKERDIR/appdata/beets/custom-cont-init.d:/custom-cont-init.d
      - $DOCKERDIR/data/media/music:/music
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      ### Traefik
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.beets-rtr.entrypoints=websecure"
      - "traefik.http.routers.beets-rtr.rule=Host(`beets.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.beets-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.beets-rtr.service=beets-svc"
      - "traefik.http.services.beets-svc.loadbalancer.server.port=8337"
      ### Homepage
      - "homepage.group=Tools"
      - "homepage.name=Beets"
      - "homepage.icon=beets.png"
      - "homepage.href=https://beets.$DOMAINNAME"
      - "homepage.description=Music Library Manager"
      ### Ofelia
      - "ofelia.enabled=true"
      - "ofelia.job-exec.beets-import.schedule=@every 6h"
      - "ofelia.job-exec.beets-import.command=sh -c 'export BEETSDIR=/config FPCALC=/usr/bin/fpcalc && /lsiopy/bin/beet import -q /music'"
